### ISSUE TITLE
syncImages()

### ISSUE THREAD

**Issue by riccamastellone** [Seba0691/Tinfinity#2]
[Qua](https://github.com/Seba0691/Tinfinity/blob/master/Tinfinity/EditProfileViewController.swift#L89) chiamo il syncImages() che fa il push locale -> remoto delle immagini del profilo.
E' corretto farlo li ? Idealmente è da chiamare quando ne viene modificata una.
Bisognerebbe anche fare locale <- remoto da fare quando apri l'app, ma anche li, non saprei dove chiamarlo.
Sarebbe carino fra l'altro, e questo lo lascio ad @albe91 , cambiare la pagina del proprio profilo così che posso scorrere alla Tinder anche le mie di immagini

**Comment by ghost** [comment]
Io avevo evitato apposta per non renderlo identico a tinder, ma ok provvederò 😁

Inviato da iPhone

**Comment by riccamastellone** [comment]
Eh ma considera che servirà una view per la visualizzazione del profilo di terzi (quando tappi sulla mappa) e tanto vale utilizzarla anche per se stessi.
Adesso inizio a fare anche la fetchImages() che va dentro user e non account - nota che esisterà comunque la fetchImage() che prende solo quella del profilo e nel caso di retrieveProfileFromServer vengono chiamate una dopo l'altra

**Comment by riccamastellone** [comment]
Ho riscritto il funzionamento della gestione immagini sia lato server che client e sembra andare:
Adesso non esiste più il campo 'image' ma abbiamo l'oggetto 'images' in cui l'elemento "0" (nota gli apici, è un oggetto non un array) rappresenta l'immagine principale.
All'interno non vi è più l'url ma direttamente l'immagine che è stata scaricata dal server e salvata in base64.
Allo stesso modo, quando vengono aggiunge immagini, il client spara al server il base64 e lo infila li dentro.

**Comment by riccamastellone** [comment]
Perdonami i mille messaggi. 
Ho aggiunto in ImageUtil resize() così possiamo fare il downsize delle immagini che FB ci passa che son troppo grandi e fanno si che tutte le richieste da / verso il server siano lentissime.
Tanto non ci serve avere l'originale: facciamo il resize appena presa e teniamo sempre quella.
@albe91 sai tu dove metterlo, quindi ti lascio anche questo compito!

**Comment by ghost** [comment]
Ho spostato la push nella funzione di unwindToHome, ma ho notato che così la UI si blocca quando viene eseguita quella azione, quindi bisognerà renderla asincrona come funzione. Un dubbio: è sensato che tutte le volte facciamo la push delle immagini? non andrebbe fatta una push solo dell'immagine aggiunta/editata? mi pare più sensato

**Comment by riccamastellone** [comment]
Si infatti, per questo chiedevo a te dove questo fosse!
La richiesta http dovrebbe già essere asincrona in quanto non aspetta la
risposta, ma nell'encodare e inviare ci mette del tempo. Investigherò!
