### ISSUE TITLE
FB Image Picker

### ISSUE THREAD

**Issue by riccamastellone** [Seba0691/Tinfinity#3]
Bisogna sistemare l'image picker di FB che di base funziona ma ha una UX disastrosa.
@albe91 hai idea delle causa di tutti i vari problemi?

**Comment by ghost** [comment]
Ti riferisci alla dimensione delle immagini di copertina degli album e al fatto che si blocca mentre carica le immagini?

edit: comunque si, va revisionato un po tutto il processo di caricamento immagini, al posto di aspettare che si carichino tutte dovremmo mettere dei placeholder che si aggiornano una volta scaricate.
